[package]
name = "kumarion/canvasdraw"
description = "Fork of Ethanthegrand/canvasdraw with some additional features."
version = "0.0.2"
license = "MIT"
authors = ["Kumarion (https://github.com/Kumarion)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]