[package]
name = "kumarion/uiparticle"
description = "Forked from UIParticle on the DevForum."
version = "0.0.1"
license = "MIT"
authors = ["Kumarion (https://github.com/Kumarion)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"